### ISSUE TITLE
Don't use 64-bit integers on 32-bit platforms

### ISSUE THREAD

**Issue by nwellnhof** [swenson/sort#39]
It should probably work to globally replace

- `uint64_t` with `size_t` and
- `int64_t` with `ptrdiff_t` (or preferably `size_t` as well unless signed integers are really required)

**Comment by swenson** [comment]
Oh, yes. It looks like we already use `size_t` inconsistently, and this is definitely something we should be more consistent about.

I can work on a fix for this in the next few days hopefully.

Thanks for pointing this is out!

**Comment by swenson** [comment]
I was able to eliminate `uint64_t` and nearly all uses of `int64_t`.

There was one function used in timsort that relies on signed arithmetic that I was not able to easily workaround. `ptrdiff_t` is not guaranteed to be big enough to hold most `size_t` (i.e., `ptrdiff_t` might be 32 bits, since it is related to pointers and not memory size), so I had to keep `int64_t` in that one function.

**Comment by nwellnhof** [comment]
On 32-bit systems, `ptrdiff_t` should be the same as `int32_t` and this can be a problem with `char` arrays that have more than 2G elements. If `sort.h` is supposed to work with such arrays, you really need 64-bit integers or some other workaround. But a 2G `char` array would typically be sorted with counting sort.

The C standard also doesn't guarantee that `ptrdiff_t` has at least as many bits as `size_t`, but I don't think there's a platform where this doesn't hold true. Unfortunately, C89 doesn't require `SIZE_MAX` and `PTRDIFF_MAX`. The following compile-time check works on every platform that provides a C99-conformant `stdint.h`:

~~~ c
#include <stdint.h>

#if defined(SIZE_MAX) && defined(PTRDIFF_MAX) && PTRDIFF_MAX < SIZE_MAX / 2
  #error Unexpected size of ptrdiff_t
#endif
~~~

(For C++ you'd need `std::numeric_limits`.)
